version: 2
jobs:
  build:
    machine: true
    # machine: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: Update PATH
          command: "echo 'export PATH=${PWD}/miniconda/bin:${PATH}' >> ${BASH_ENV}"

      - run:
          name: Setup Conda
          command: make conda-tests

      - run:
          name: Run Unit testing
          command: male all-unit-tests

      - run:
          name: Run System testing
          command: make ci-tests
