version: 2
jobs:
  build:
    machine: true
    # machine: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - restore_cache:
          keys:
            - snakemake-{{ checksum ".circleci/setup.sh" }}

      - run:
          name: Update PATH
          command: "echo 'export PATH=${PWD}/miniconda/bin:${PATH}' >> ${BASH_ENV}"

      - run:
          name: Setup Conda
          command: bash .circleci/setup.sh

      - save_cache:
          key: snakemake-{{ checksum ".circleci/setup.sh" }}
          paths:
            - miniconda

      - run:
          name: Run Unit testing
          command: |
            source activate rna-count-salmon
            pytest -v scripts/prepare_config.py scripts/prepare_design.py scripts/aggregate_samples.py

      - run:
          name: Run System testing
          command: |
            source activate rna-count-salmon
            python3.7 scripts/prepare_design.py tests/reads/ -o tests/design.tsv
            python3.7 scripts/prepare_config.py genomes/transcriptome.fasta --salmon-index-extra ' --kmerLen 5 ' --salmon-quant-extra ' --noBiasLengthThreshold --minAssignedFrags 1 --noEffectiveLengthCorrection --noLengthCorrection --fasterMapping --noFragLengthDist --allowDovetail --numPreAuxModelSamples 0 --numAuxModelSamples 0 ' --aggregate --libType "ISF" --workdir tests -o tests/config.yaml -d tests/design.tsv
            snakemake -s Snakefile --use-conda -j 1 --force
            snakemake -s Snakefile --use-conda -j 1 --report
