name: rna-count-salmon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python ==3.7.3
  - pytest ==5.1.2
  - datrie ==0.8
  - git ==2.20.1
  - jinja2 ==2.10.1
  - pygraphviz ==1.5
  - flask ==1.1.1
  - pandas ==0.25.1
  - zlib ==1.2.11
  - openssl ==1.1.1c
  - networkx ==2.3
  - snakemake ==5.5.4
