name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Pipeline testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup conda
      run: bash .github/workflows/setup.sh
    - name: Setup workflow environment
      run: make conda-tests
    - name: Scripts unit-testing
      run: make all-unit-tests
    - name: Run Wnakemake-workflow
      run: make ci-tests
